policy_config_mapping:
    filtering_attributes:
        serviceProfileParameters: serviceProfileParameters
        hypervisor: hypervisor
        cloudVersion: cloud_version
        cloudType: cloud_type
        dataPlane: dataplane
        networkRoles: network_roles
        complex: complex
        state: state
        country: country
        geoRegion: geo_region
        exclusivityGroups: exclusivity_groups
        replicationRole: replication_role
        customerId: customer_id
        serviceResourceId: service-type
        equipmentRole: equipment-role
        modelInvariantId: model-invariant-id
        modelVersionId: model-version-id
        cloudRegionId: cloud-region-id
        orchestrationStatus: orchestration-status
        provStatus: prov-status
        cloudRegion: cloud-region
    cloud_region_attributes: 
        serviceRequests: service-requests
        cloudRequests: cloud-requests
    passthrough_attributes: {}
    candidates:
        # for (k1, v1), if k1 is in demand, set prop[k2] = _get_candidates(demand[k1])
        excludedCandidates: excluded_candidates
        requiredCandidates: required_candidates
    extra_fields:
        # we have [k1, k2, k3, k4] type items and x is policy-content-properties
        # if x[k1] == k2: set prop[k3] = k4
        - [inventoryType, cloud, region, {get_param: CHOSEN_REGION}]
